//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class BaseDB 
{
	private string dbAddress
	{
		get;
		set;
	}

	private string dbPass
	{
		get;
		set;
	}

	private string dbLogin
	{
		get;
		set;
	}

	public virtual void Connect()
	{
		throw new System.NotImplementedException();
	}

}

