//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using CapstoneModelLib.GeneratedCode;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Customer : User
{
    public Customer(int ID, string userName, byte[] passHash, string fName, string lName, Address address) : base(ID, userName, passHash, fName, lName, address)
    {
    }

    public string _id { get; set; } = DateTime.Now.ToString();

    public virtual void CreateOrder()
	{
        /*
         *  Creates a new order and adds it to the database for the user
         */
        
	}

	public virtual bool PlaceOrder(Order order)
	{
        /*
         *  Returns wheather the order selected has been placed. Return false for now
         */
        return false;
    }

    public virtual void VerifyOrder()
	{
        /*
         *  Method to verify if the order has been succesfully verified
         */
    }

    public virtual bool becomeAShopper()
	{
        /*
         *  adds the customer to the Shopper database and makes them a shopper
         */
        throw new System.NotImplementedException();
	}

}

