//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class CustomerActionDB : ShopperActionsDB
{
	private User curUser
	{
		get;
		set;
	}

	public virtual List<Order> GetPrevoisOrders()
	{
		throw new System.NotImplementedException();
	}

	public virtual bool PlaceOrder(Order order)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool BecomeShopper()
	{
		throw new System.NotImplementedException();
	}

	public virtual void RateShopper(Order order)
	{
		throw new System.NotImplementedException();
	}

	public virtual void VerifyOrder(Order order)
	{
		throw new System.NotImplementedException();
	}

}

