//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Customer : User
{
	public virtual List<Order> previousOrders
	{
		get;
		set;
	}

	public virtual void CreateOrder()
	{
		throw new System.NotImplementedException();
	}

	public virtual bool PlaceOrder(Order order)
	{
		throw new System.NotImplementedException();
	}

	public virtual void VerifyOrder()
	{
		throw new System.NotImplementedException();
	}

	public virtual bool becomeAShopper()
	{
		throw new System.NotImplementedException();
	}

	public virtual void RateShopper(Order order)
	{
		throw new System.NotImplementedException();
	}

}

