//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using CapstoneModelLib.GeneratedCode;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Order
{
	public virtual List<OrderItem> placedOrder
	{
		get;
		set;
	}

	public virtual int customerID
	{
		get;
		set;
	}

	public virtual int shopperID
	{
		get;
		set;
	}

	public virtual Address deliveryAddress
	{
		get;
		set;
	}

	public virtual Address storeAddress
	{
		get;
		set;
	}

    private List<OrderItem> foundItems
    {
        get;
        set;
    } = new List<OrderItem>();

    private List<OrderItem> missingItems
    {
        get;
        set;
    } = new List<OrderItem>();

	public virtual double EstimatedCost
	{
		get;
		set;
	}

	public virtual int orderID
	{
		get;
		set;
	}

	public virtual bool notifyCustomer
	{
		get;
		set;
	}

	public virtual void FoundItem(OrderItem item)
	{
		//throw new System.NotImplementedException();
	}

	public virtual void MoveItemToMissing(OrderItem item)
	{
		throw new System.NotImplementedException();
	}

	public virtual void FoundMissingItem(OrderItem item)
	{
		throw new System.NotImplementedException();
	}

	public virtual void GetToStore()
	{
		throw new System.NotImplementedException();
	}

	public virtual void DeliverOrder()
	{
		throw new System.NotImplementedException();
	}

	public virtual Double EstimateCost()
	{
		throw new System.NotImplementedException();
	}

}

