//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using CapstoneModelLib.GeneratedCode;

public class Shopper : Customer
{
    public Shopper(int ID, string userName, string passHash, string fName, string lName) : base(ID, userName, passHash, fName, lName)
    {
    }

    private int shopperID
	{
		get;
		set;
	}

	public virtual double rating
	{
		get;
		set;
	}

	public virtual double radius
	{
		get;
		set;
	}

	private Coordinate radiusCenter
	{
		get;
		set;
	}

	public virtual bool isAvailable
	{
		get;
		set;
	}

	public virtual bool inStandBy
	{
		get;
		set;
	}

	private List<Order> deliveredOrders
	{
		get;
		set;
	}

	private void RecieveOrder(Order order)
	{
        //This method would be connected to the database model class and would allow a shopper to recieve an order
		throw new System.NotImplementedException();
	}

}

