//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using CapstoneModelLib.GeneratedCode;
using MongoDB.Bson;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class User
{
    public User(int ID, string userName, byte[] passHash, string fName, string lName, Address address)
    {
        userID = ID;
        Username = userName;
        this.passHash = passHash;
        this.fName = fName;
        this.lName = lName;
        streetAddress = address;
    }

	public string Username
	{
		get;
		set;
	}

	public Address streetAddress
	{
		get;
		private set;
	}

	public byte[] passHash
	{
		get;
		private set;
	}

	public string fName
	{
		get;
		private set;
	}

	public string lName
	{
		get;
		private set;
	}

	public virtual int userID
	{
		get;
		set;
	}

	public virtual bool Login(string enteredPass)
	{
        //would connect to the UserActionDBClass and allow them to login this method
		throw new System.NotImplementedException();
	}

    public virtual BsonDocument GetBson()
    {
        BsonDocument bson = new BsonDocument
        {
            {"userID", BsonValue.Create(userID) },
            {"fName", BsonValue.Create(fName) },
            {"lName", BsonValue.Create(lName) },
            {"username", BsonValue.Create(Username) },
            {"passhash", passHash },
            {"address", streetAddress.ToBson() }
        };

        return bson;
    }
}

