//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class UserActionsDB : BaseDB
{
	private User curUser
	{
		get;
		set;
	}

	public virtual User SignIn(String userName, string Password)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool CreateUser(User  user)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool EditUser(User user)
	{
		throw new System.NotImplementedException();
	}

}

