//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using CapstoneModelLib.GeneratedCode;
using MongoDB.Bson;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class User
{
    public User(int ID, string userName, byte[] passHash, string fName, string lName, Address address)
    {
        userID = ID;
        Username = userName;
        this.passHash = passHash;
        this.fName = fName;
        this.lName = lName;
        Address = address;
        _id = DateTime.Now.ToString();
    }

    public string _id { get; set; }

    public string Username
    {
        get;
        set;
    }

    public Address Address
    {
        get;
        private set;
    }

    public byte[] passHash
    {
        get;
        private set;
    }

    public string fName
    {
        get;
        private set;
    }

    public string lName
    {
        get;
        private set;
    }

    public virtual int userID
    {
        get;
        set;
    }
}

