//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureSQLConnection.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CapstoneDBEntities : DbContext
    {
        public CapstoneDBEntities()
            : base("name=CapstoneDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<completedOrder> completedOrders { get; set; }
        public virtual DbSet<curPlacedOrder> curPlacedOrders { get; set; }
        public virtual DbSet<Shopper> Shoppers { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
