#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PersonalShopperApp.Resource", IsApplication=true)]

namespace PersonalShopperApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f040000
			public const int states_array = 2130968576;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050004
			public const int AddItem = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int AddItemMaxPrice = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int AddItemName = 2131034114;
			
			// aapt resource value: 0x7f05001a
			public const int CreateNext = 2131034138;
			
			// aapt resource value: 0x7f050042
			public const int DeclineOrder = 2131034178;
			
			// aapt resource value: 0x7f050026
			public const int EditItem = 2131034150;
			
			// aapt resource value: 0x7f050025
			public const int EditItemMaxPrice = 2131034149;
			
			// aapt resource value: 0x7f050024
			public const int EditItemName = 2131034148;
			
			// aapt resource value: 0x7f050033
			public const int EstimatedCost = 2131034163;
			
			// aapt resource value: 0x7f050005
			public const int ItemNameView = 2131034117;
			
			// aapt resource value: 0x7f05002f
			public const int MissingItemNameView = 2131034159;
			
			// aapt resource value: 0x7f05002c
			public const int Password = 2131034156;
			
			// aapt resource value: 0x7f05000c
			public const int RecieveOrders = 2131034124;
			
			// aapt resource value: 0x7f05002b
			public const int Username = 2131034155;
			
			// aapt resource value: 0x7f050041
			public const int acceptOrder = 2131034177;
			
			// aapt resource value: 0x7f050006
			public const int actualPrice = 2131034118;
			
			// aapt resource value: 0x7f050044
			public const int backToOrder = 2131034180;
			
			// aapt resource value: 0x7f05000b
			public const int becomeShopper = 2131034123;
			
			// aapt resource value: 0x7f050009
			public const int button1 = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int button2 = 2131034122;
			
			// aapt resource value: 0x7f050032
			public const int button3 = 2131034162;
			
			// aapt resource value: 0x7f050023
			public const int confirmDelivery = 2131034147;
			
			// aapt resource value: 0x7f050034
			public const int confirmOrder = 2131034164;
			
			// aapt resource value: 0x7f05001f
			public const int creApt = 2131034143;
			
			// aapt resource value: 0x7f05001c
			public const int creCity = 2131034140;
			
			// aapt resource value: 0x7f050019
			public const int creConPass = 2131034137;
			
			// aapt resource value: 0x7f050015
			public const int creFirstName = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int creLastName = 2131034134;
			
			// aapt resource value: 0x7f050018
			public const int crePassword = 2131034136;
			
			// aapt resource value: 0x7f05001e
			public const int creStates = 2131034142;
			
			// aapt resource value: 0x7f05001b
			public const int creStreetAdd = 2131034139;
			
			// aapt resource value: 0x7f050017
			public const int creUsername = 2131034135;
			
			// aapt resource value: 0x7f05001d
			public const int creZip = 2131034141;
			
			// aapt resource value: 0x7f050022
			public const int delvActCost = 2131034146;
			
			// aapt resource value: 0x7f050040
			public const int delvAddressView = 2131034176;
			
			// aapt resource value: 0x7f05003e
			public const int estCost = 2131034174;
			
			// aapt resource value: 0x7f050020
			public const int finishCreation = 2131034144;
			
			// aapt resource value: 0x7f050027
			public const int foundItems = 2131034151;
			
			// aapt resource value: 0x7f050043
			public const int foundItemsList = 2131034179;
			
			// aapt resource value: 0x7f050028
			public const int homeWelcome = 2131034152;
			
			// aapt resource value: 0x7f050007
			public const int itemMissing = 2131034119;
			
			// aapt resource value: 0x7f050021
			public const int linearLayout1 = 2131034145;
			
			// aapt resource value: 0x7f05000d
			public const int listView1 = 2131034125;
			
			// aapt resource value: 0x7f050008
			public const int map = 2131034120;
			
			// aapt resource value: 0x7f05002e
			public const int missingItems = 2131034158;
			
			// aapt resource value: 0x7f050045
			public const int missingItemsList = 2131034181;
			
			// aapt resource value: 0x7f050030
			public const int missingactualPrice = 2131034160;
			
			// aapt resource value: 0x7f050031
			public const int orderedItems = 2131034161;
			
			// aapt resource value: 0x7f050035
			public const int prevDeliveries = 2131034165;
			
			// aapt resource value: 0x7f05002a
			public const int prevDelv = 2131034154;
			
			// aapt resource value: 0x7f050029
			public const int prevOrder = 2131034153;
			
			// aapt resource value: 0x7f050036
			public const int prevOrdersList = 2131034166;
			
			// aapt resource value: 0x7f05003d
			public const int shopperViewOrder = 2131034173;
			
			// aapt resource value: 0x7f05002d
			public const int signIn = 2131034157;
			
			// aapt resource value: 0x7f050001
			public const int space1 = 2131034113;
			
			// aapt resource value: 0x7f05000e
			public const int space2 = 2131034126;
			
			// aapt resource value: 0x7f050010
			public const int space3 = 2131034128;
			
			// aapt resource value: 0x7f050012
			public const int space4 = 2131034130;
			
			// aapt resource value: 0x7f050014
			public const int space5 = 2131034132;
			
			// aapt resource value: 0x7f05003f
			public const int storeAddressView = 2131034175;
			
			// aapt resource value: 0x7f05003c
			public const int storeApt = 2131034172;
			
			// aapt resource value: 0x7f050039
			public const int storeCity = 2131034169;
			
			// aapt resource value: 0x7f05003b
			public const int storeStates = 2131034171;
			
			// aapt resource value: 0x7f050038
			public const int storeStreetAdd = 2131034168;
			
			// aapt resource value: 0x7f05003a
			public const int storeZip = 2131034170;
			
			// aapt resource value: 0x7f050000
			public const int textView1 = 2131034112;
			
			// aapt resource value: 0x7f05000f
			public const int textView2 = 2131034127;
			
			// aapt resource value: 0x7f050011
			public const int textView3 = 2131034129;
			
			// aapt resource value: 0x7f050013
			public const int textView4 = 2131034131;
			
			// aapt resource value: 0x7f050037
			public const int waitingOrders = 2131034167;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int AddOrderItem = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int AssignPriceToItem = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int BaseMaps = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int BecomeAShopper = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Checkout = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int CreateAccount1 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int CreateAccount2 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int DeliverOrder = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int EditOrderItem = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int FoundItems = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Home = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Main = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int MissingItems = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int MissingToFoundItem = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int PlaceOrder = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int PreviousDeliveries = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int PreviousOrders = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ReceiveOrder = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int SetStoreAddress = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int Settings = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ShopperViewOrder = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int TakeOrderFromWaitingList = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ViewFound = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ViewMissing = 2130837527;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
