//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using MongoDB.Bson;
using MongoDB.Driver;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Text;

namespace PersonalShopperApp.Models
{
    public class BaseDB
    {
        public BaseDB()
        {
            cb = new SqlConnectionStringBuilder();
            cb.DataSource = "shopltft.database.windows.net";
            cb.UserID = "JPriem";
            cb.Password = "TeaganRory12!";
            cb.InitialCatalog = "CapstoneDB";
            connection = new SqlConnection(cb.ConnectionString);
            //Comment for now Will swich to mongoDB ASP .NET service for the application
        }

        public string dbAddress
        {
            get;
            set;
        }

        private string dbPass
        {
            get;
            set;
        }

        private string dbLogin
        {
            get;
            set;
        }

        public SqlConnection connection { get; private set; }
        public SqlConnectionStringBuilder cb { get; private set; }

        public bool Connect()
        {
            //var connectionString = "mongodb://192.168.1.200:27017";
            //var client = new MongoClient(new MongoUrl("mongodb://127.0.0.1:27017"));
            bool isConnected = false;
            //client = new MongoClient(new MongoUrl(dbAddress));
            //client.ListDatabases();
            //var state = client.Cluster.Description.State;
            //if (state.ToString() == "Connected")
            //{
            //    isConnected = true;
            //}
            //return isConnected;

            try
            {
                //Source = shopltft.database.windows.net; Initial Catalog = CapstoneDB; Persist Security Info = True; User ID = JPriem; Password = ***********
                using (connection)
                {
                    connection.Open();
                    ConnectionState state = connection.State;
                    if(state == ConnectionState.Open)
                    {
                        isConnected = true;
                    }
                }
            }
            catch (SqlException e)
            {
                Console.WriteLine(e.ToString());
            }
            return isConnected;
        }
        
    }

}