//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using MongoDB.Bson;
using MongoDB.Driver;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace PersonalShopperApp.Models
{
    public class BaseDB
    {
        public BaseDB(string dbAddress)
        {
            this.dbAddress = dbAddress;
            //Comment for now Will swich to mongoDB ASP .NET service for the application
        }

        public string dbAddress
        {
            get;
            set;
        }

        private string dbPass
        {
            get;
            set;
        }

        private string dbLogin
        {
            get;
            set;
        }

        public MongoClient client { get; private set; }

        public bool Connect()
        {
            //var connectionString = "mongodb://192.168.1.200:27017";
            //var client = new MongoClient(new MongoUrl("mongodb://127.0.0.1:27017"));
            bool isConnected = false;
            client = new MongoClient(new MongoUrl(dbAddress));
            client.ListDatabases();
            var state = client.Cluster.Description.State;
            if (state.ToString() == "Connected")
            {
                isConnected = true;
            }
            return isConnected;
        }

    }

}