//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using MongoDB.Bson;
using MongoDB.Driver;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Text;

namespace PersonalShopperApp.Models
{
    public class BaseDB
    {
        public BaseDB(string dbAddress)
        {
            this.dbAddress = dbAddress;
            var cb = new SqlConnectionStringBuilder();
            //Comment for now Will swich to mongoDB ASP .NET service for the application
        }

        public string dbAddress
        {
            get;
            set;
        }

        private string dbPass
        {
            get;
            set;
        }

        private string dbLogin
        {
            get;
            set;
        }

        public MongoClient client { get; private set; }

        public bool Connect()
        {
            //var connectionString = "mongodb://192.168.1.200:27017";
            //var client = new MongoClient(new MongoUrl("mongodb://127.0.0.1:27017"));
            //bool isConnected = false;
            //client = new MongoClient(new MongoUrl(dbAddress));
            //client.ListDatabases();
            //var state = client.Cluster.Description.State;
            //if (state.ToString() == "Connected")
            //{
            //    isConnected = true;
            //}
            //return isConnected;

            try
            {
                //Source = shopltft.database.windows.net; Initial Catalog = CapstoneDB; Persist Security Info = True; User ID = JPriem; Password = ***********
                var cb = new SqlConnectionStringBuilder();
                cb.DataSource = "shopltft.database.windows.net";
                cb.UserID = "JPriem";
                cb.Password = "TeaganRory12!";
                cb.InitialCatalog = "CapstoneDB";

                using (SqlConnection connection = new SqlConnection(cb.ConnectionString))
                {
                    Console.WriteLine("\nQuery data example:");
                    Console.WriteLine("=========================================\n");

                    connection.Open();
                    StringBuilder sb = new StringBuilder();
                    sb.Append("SELECT * ");
                    sb.Append("FROM dbo.Users ");
                    String sql = sb.ToString();

                    using (SqlCommand command = new SqlCommand(sql, connection))
                    {
                        using (SqlDataReader reader = command.ExecuteReader())
                        {
                            while (reader.Read())
                            {
                                Console.WriteLine(reader.GetInt32(0));
                            }
                        }
                    }
                }
            }
            catch (SqlException e)
            {
                Console.WriteLine(e.ToString());
            }
            Console.ReadLine();
            return true;
        }

    }

}