//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace PersonalShopperApp.Models
{
    public class OrderActionsDB : BaseDB
    {
        public OrderActionsDB(string dbAddress) : base(dbAddress)
        {
        }

        public virtual List<Order> curOrders
        {
            get;
            set;
        }

        public virtual void AssignOrder()
        {
            throw new System.NotImplementedException();
        }

        public virtual void NotifyCustomer(Order order)
        {
            throw new System.NotImplementedException();
        }

    }

}