//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
namespace PersonalShopperApp.Models
{
    public class ShopperActionsDB : BaseDB
    {
        public ShopperActionsDB(string dbAddress) : base(dbAddress)
        {
        }

        public virtual void GetCompletedOrders()
        {
            throw new System.NotImplementedException();
        }

        public virtual void ReciverOrder(Order order)
        {
            /*
             * This method takes an order off of the curPlacedOrders table
             */
        }

    }

}