//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Android.OS;
using Java.IO;
using MongoDB.Bson;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Android.Runtime;

namespace PersonalShopperApp.Models
{
    public class User: IParcelable
    {
        public User(int ID, string userName, byte[] passHash, string fName, string lName, Address address)
        {
            userID = ID;
            Username = userName;
            this.passHash = passHash;
            this.fName = fName;
            this.lName = lName;
            Address = address;
        }

        public string _id { get; set; } = DateTime.Now.ToString();

        public string Username
        {
            get;
            set;
        }

        public Address Address
        {
            get;
            private set;
        }

        public byte[] passHash
        {
            get;
            private set;
        }

        public string fName
        {
            get;
            private set;
        }

        public string lName
        {
            get;
            private set;
        }

        public virtual int userID
        {
            get;
            set;
        }

        public int DescribeContents()
        {
            throw new NotImplementedException();
        }

        

        public void WriteToParcel(Parcel dest, [GeneratedEnum] ParcelableWriteFlags flags)
        {
            throw new NotImplementedException();
        }
    }

}